name: deploy document with hugo

on:
  push:
    branches:
      master

env:
  SSH_ACTIONS: false
  DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  HOST: xunqinji.top
  USER: root
  DIR: /www/wwwroot/pro.xunqinji.top/

jobs:
  build-hugo-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install hugo 
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb 
          sudo dpkg -i hugo.deb
          type hugo
      - name: create hugo sites
        run: |
          hugo new site ~/docs
          cp docs/*.org ~/docs/content/
      - name: install hugo theme
        run: |
          cd ~/docs
          git init
          git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
          echo 'theme = "ananke"' >> config.toml
          sed -i 's/example\.org/xunqinji\.top\/hugo/g' config.toml
          echo "Done with settings!"
      - name: SSH connection to Actions
        uses: P3TERX/debugger-action@master
        if: env.SSH_ACTIONS == 'true'
      - name: manually deploy hugo site
        run: |
          bash bin/deploy.sh
          echo "Done!"
