name: deploy document with hugo

on:
  push:
    branches:
      master

jobs:
  build-hugo-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install hugo 
        run: |
          sudo apt-get update && sudo apt-get install wget
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb 
          sudo dpkg -i hugo.deb
          type hugo
      - name: create hugo sites
        run: |
          hugo new site ~/docs
          cp docs/*.org ~/docs/content/
          cd ~/docs
          hugo build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: be4d2fb7161448bafcb73cad812b12ad0d8dde2b 
          BRANCH: gh-hugo-pages
          FOLDER: public
